# -*- coding: utf-8 -*-
"""1D_wildlandfire.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Coz2BtluDEoYvHY8v4Vae3SoDbxD2Ki
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from numpy import meshgrid
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader, Dataset
from torch.autograd import gradcheck
from numpy import exp, mod, meshgrid, cos, sin, exp, pi
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import shift
from math import sqrt
from scipy.sparse import diags
from scipy.linalg import cholesky

import os
impath = "./data/Wildlandfire_1d/"
immpath = "./plots/Wildlandfire_1d/"
os.makedirs(impath, exist_ok=True)
os.makedirs(immpath, exist_ok=True)

"""# Crossing waves example

## Create data for example model
"""

seed = 1
np.random.seed(seed)
torch.manual_seed(seed)

dtype  = torch.float32
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
pretrained_load = True
print(device)

# Load the wild land fire data
q = np.load('data/Wildlandfire_1d/Original_data/SnapShotMatrix558.49.npy', allow_pickle=True)
X = np.load('data/Wildlandfire_1d/Original_data/1D_Grid.npy', allow_pickle=True)
t = np.load('data/Wildlandfire_1d/Original_data/Time.npy', allow_pickle=True)
x = X[0]
dx = x[1] - x[0]
dt = t[1] - t[0]
Nx = int(np.size(x))
Nt = int(np.size(t))
Q = q[:Nx, :]

# Normalize the input data
Q = (Q - Q.min())/(Q.max() - Q.min())

# Compute the actual shift
c_left = np.zeros(Nt)
front_pos_left = np.zeros(Nt)
shift_left = np.zeros(Nt)

c_right = np.zeros(Nt)
front_pos_right = np.zeros(Nt)
shift_right = np.zeros(Nt)

for i in range(0, Nt):
    gradVar = np.gradient(Q[:, i], dx, edge_order=2)
    del_t = t[i] - t[0]

    front_pos_right[i] = x[np.argmin(gradVar)]  # Right going wave
    front_pos_left[i] = x[np.argmax(gradVar)]  # Left going wave

    del_x_left = front_pos_left[i] - front_pos_left[0]
    shift_left[i] = del_x_left
    c_left[i] = (del_x_left / del_t).squeeze()

    del_x_right = front_pos_right[i] - front_pos_right[0]
    shift_right[i] = del_x_right
    c_right[i] = (del_x_right / del_t).squeeze()

c_left[0] = c_left[1]
c_right[0] = c_right[1]


x_device = torch.tensor(x.copy(),  dtype=dtype, device=device)
t_device = torch.tensor(t.copy(),  dtype=dtype, device=device)
center_matrix = torch.tensor(x[-1] // 2, dtype=dtype, device=device)

"""## Define a model"""

@torch.jit.script
def nuclear_norm(input_matrix: torch.Tensor) -> torch.Tensor:
    # Forward computation
    return torch.linalg.matrix_norm(input_matrix, ord="nuc")


@torch.jit.script
def nuclear_norm_grad(input_matrix: torch.Tensor, grad_output: torch.Tensor) -> torch.Tensor:
    u, s, v = torch.linalg.svd(input_matrix, full_matrices=False)
    rank = (s > 0).sum().item()
    eye_approx = torch.diag_embed((s > 0).to(input_matrix.dtype)[:rank])
    grad_input = torch.matmul(u[:, :rank], eye_approx)
    grad_input = torch.matmul(grad_input, v[:, :rank].transpose(-2, -1))
    return grad_input * grad_output.unsqueeze(-1).unsqueeze(-1)


class NuclearNormAutograd(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input_matrix):
        ctx.save_for_backward(input_matrix)
        return nuclear_norm(input_matrix)

    @staticmethod
    def backward(ctx, grad_output):
        input_matrix, = ctx.saved_tensors
        return nuclear_norm_grad(input_matrix, grad_output)

class ShapeShiftNet(nn.Module):
    def __init__(self, N_in, N_in_c, N_out, N_out_c, N_hidden, N_layers, x, t, center_matrix):
        super(ShapeShiftNet, self).__init__()

        self.register_buffer('x_flat', x)
        self.register_buffer('t_flat', t)
        self.register_buffer('center_matrix', center_matrix)

        activation = torch.nn.Tanh

        # network for f^1
        self.fc_in_frame1 = torch.nn.Sequential(*[torch.nn.Linear(N_in, N_hidden), activation()])
        # Hidden layers.
        self.hidden_layers_frame1 = torch.nn.Sequential(*[torch.nn.Sequential(*[torch.nn.Linear(N_hidden, N_hidden), activation()])
                                                          for _ in range(N_layers - 1)])
        # Output layer.
        self.fc_out_frame1 = torch.nn.Linear(N_hidden, N_out)


        # network for f^2
        self.fc_in_frame2 = torch.nn.Sequential(*[torch.nn.Linear(N_in, N_hidden), activation()])
        # Hidden layers.
        self.hidden_layers_frame2 = torch.nn.Sequential(*[torch.nn.Sequential(*[torch.nn.Linear(N_hidden, N_hidden), activation()])
                                                          for _ in range(N_layers - 1)])
        # Output layer.
        self.fc_out_frame2 = torch.nn.Linear(N_hidden, N_out)


        # network for f^3
        self.fc_in_frame3 = torch.nn.Sequential(*[torch.nn.Linear(N_in, N_hidden), activation()])
        # Hidden layers.
        self.hidden_layers_frame3 = torch.nn.Sequential(*[torch.nn.Sequential(*[torch.nn.Linear(N_hidden, N_hidden), activation()])
                                                          for _ in range(N_layers - 1)])
        # Output layer.
        self.fc_out_frame3 = torch.nn.Linear(N_hidden, N_out)


        # Shift 1
        # Input layer.
        self.shift_in1 = torch.nn.Sequential(*[torch.nn.Linear(N_in_c, N_hidden), activation()])
        # Hidden layers.
        self.hidden_layers1 = torch.nn.Sequential(*[torch.nn.Sequential(*[torch.nn.Linear(N_hidden, N_hidden), activation()])
                                                          for _ in range(N_layers - 1)])
        # Output layer.
        self.shift_out1 = torch.nn.Linear(N_hidden, N_out_c)


    def forward(self):
        ################################ Shifts ####################################
        c1 = self.shift_in1(self.t_flat)
        for layer in self.hidden_layers1:
            c1 = layer(c1)
        c1 = self.shift_out1(c1)

        ################################ Frames ####################################
        x_shifted1 = self.x_flat - c1 * self.t_flat - self.center_matrix
        f1 = self.fc_in_frame1(torch.cat((x_shifted1, self.t_flat), dim=1))
        for layer in self.hidden_layers_frame1:
            f1 = layer(f1)
        f1 = self.fc_out_frame1(f1)

        x_shifted3 = self.x_flat + c1 * self.t_flat - self.center_matrix
        f3 = self.fc_in_frame3(torch.cat((x_shifted3, self.t_flat), dim=1))
        for layer in self.hidden_layers_frame3:
            f3 = layer(f3)
        f3 = self.fc_out_frame3(f3)



        f1_without_shift = self.fc_in_frame1(torch.cat((self.x_flat - self.center_matrix, self.t_flat), dim=1))
        for layer in self.hidden_layers_frame1:
            f1_without_shift = layer(f1_without_shift)
        f1_without_shift = self.fc_out_frame1(f1_without_shift)

        f2_without_shift = self.fc_in_frame2(torch.cat((self.x_flat - self.center_matrix, self.t_flat), dim=1))
        for layer in self.hidden_layers_frame2:
            f2_without_shift = layer(f2_without_shift)
        f2_without_shift = self.fc_out_frame2(f2_without_shift)

        f3_without_shift = self.fc_in_frame3(torch.cat((self.x_flat - self.center_matrix, self.t_flat), dim=1))
        for layer in self.hidden_layers_frame3:
            f3_without_shift = layer(f3_without_shift)
        f3_without_shift = self.fc_out_frame3(f3_without_shift)

        return f1, f2_without_shift, f3, c1, f1_without_shift, f2_without_shift, f3_without_shift

"""## Define inputs"""

x_flat = (x_device).repeat_interleave(Nt).to(device=device, dtype=dtype).view(-1, 1)
t_flat = (t_device).repeat(Nx).to(device=device, dtype=dtype).view(-1, 1)
Q = torch.tensor(Q, dtype=dtype, device=device)

lr = 0.00005
num_epochs = 75000
lambda_star = 0.005
lambda_l1 = 0.05

"""## Call the model"""

model = ShapeShiftNet(2, 1, 1, 1, 32, 4, x_flat, t_flat, center_matrix)

if pretrained_load:
    state_dict_original = torch.load("./data/single_wave/single_wave.pth")
    state_dict_new = model.state_dict()

    for name, param in state_dict_original.items():
        if name in state_dict_new:
            if name in ("x_flat", "t_flat", "center_matrix"):
                pass
            else:
                state_dict_new[name].copy_(param)
    model.load_state_dict(state_dict_new, strict=False)

    # Copy f^1 weights into f^2
    model.fc_in_frame2.load_state_dict(model.fc_in_frame1.state_dict())
    model.hidden_layers_frame2.load_state_dict(model.hidden_layers_frame1.state_dict())
    model.fc_out_frame2.load_state_dict(model.fc_out_frame1.state_dict())

    # Copy f^1 weights into f^3
    model.fc_in_frame3.load_state_dict(model.fc_in_frame1.state_dict())
    model.hidden_layers_frame3.load_state_dict(model.hidden_layers_frame1.state_dict())
    model.fc_out_frame3.load_state_dict(model.fc_out_frame1.state_dict())

    jit_model = torch.jit.script(model)
    jit_model.to(device)
    delta = 1e-3
else:
    jit_model = torch.jit.script(model)
    jit_model.to(device)
    delta = 1e-5

optimizer = torch.optim.Adam(jit_model.parameters(), lr=lr)


for epoch in range(num_epochs + 1):
    optimizer.zero_grad()

    # Function call for the model
    f1_full, f2_full, f3_full, shift1_pred, f1_full_nos, f2_full_nos, f3_full_nos = jit_model()
    T1Q1 = f1_full.view(Nx, Nt)
    T2Q2 = f2_full.view(Nx, Nt)
    T3Q3 = f3_full.view(Nx, Nt)
    Q1 = f1_full_nos.view(Nx, Nt)
    Q2 = f2_full_nos.view(Nx, Nt)
    Q3 = f3_full_nos.view(Nx, Nt)

    frobenius_loss = torch.linalg.norm(Q - T1Q1 - T2Q2 - T3Q3, 'fro')/ torch.linalg.norm(Q, 'fro')
    l1_loss = lambda_l1 * (torch.linalg.norm(T1Q1, 1) + torch.linalg.norm(T2Q2, 1) + torch.linalg.norm(T3Q3, 1)) / torch.linalg.norm(Q, 1)
    nuclear_loss = lambda_star * (NuclearNormAutograd.apply(Q1) + NuclearNormAutograd.apply(Q2) + NuclearNormAutograd.apply(Q3))
    total_loss = frobenius_loss + nuclear_loss + l1_loss

    total_loss.backward()

    optimizer.step()

    if frobenius_loss < delta:
        print("Early stopping is triggered")
        break
    with torch.no_grad():
        if epoch % 10 == 0:
            print("\n**************************************************************")
            print(f'Epoch {epoch}/{num_epochs}, F: {frobenius_loss.item():.4f}, '
                  f'N: {nuclear_loss.item():.4f}, '
                  f'L1: {l1_loss.item():.4f}, '
                  f'T: {total_loss.item():.4f}')

# Bring everything back to CPU
Q = Q.cpu().detach().numpy()
Q_tilde = (T1Q1 + T2Q2 + T3Q3).cpu().detach().numpy()
T1Q1 = T1Q1.cpu().detach().numpy()
T2Q2 = T2Q2.cpu().detach().numpy()
T3Q3 = T3Q3.cpu().detach().numpy()
Q1 = Q1.cpu().detach().numpy()
Q2 = Q2.cpu().detach().numpy()
Q3 = Q3.cpu().detach().numpy()
shift1 = front_pos_left.copy()
shift1_numpy = shift1_pred.cpu().detach().numpy()
shift1_numpy_mat = shift1_numpy.reshape(Nx, Nt)
shift1_pred = shift1_numpy * t_flat.cpu().detach().numpy()
shift1_pred_mat = shift1_pred.reshape(Nx, Nt)
shift1_val = shift1_pred_mat.max(axis=0)



rec_err = np.linalg.norm(Q - T1Q1 - T2Q2 - T3Q3) / np.linalg.norm(Q)
print(f"RecErr: {rec_err}")

"""## Saving the results"""

torch.save(model.state_dict(), impath + 'Wildlandfire_1d.pth')
np.save(impath + 'Q.npy', Q)
np.save(impath + 'Q_tilde.npy', Q_tilde)
np.save(impath + 'T1Q1.npy', T1Q1)
np.save(impath + 'T2Q2.npy', T2Q2)
np.save(impath + 'T3Q3.npy', T3Q3)
np.save(impath + 'Q1.npy', Q1)
np.save(impath + 'Q2.npy', Q2)
np.save(impath + 'Q3.npy', Q3)
np.save(impath + 'shifts1.npy', shift1_val)
np.save(impath + 'shifts1_true.npy', shift1)

